//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DBModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    using Core;

    public partial class department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public department()
        {
            this.employees = new HashSet<employee>();
            this.Department = new List<DropDown>();
            DropDown o = new DropDown();
            o.Id = "1";
            o.Name = "Text1";
            Department.Add(o);
        }
        [Required(ErrorMessage = "Department ID Required")]
        public int deptid { get; set; }

        [Required(ErrorMessage = "Department ID Required")]
        public string Name { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> parentid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee> employees { get; set; }

        [Display(Name = "Favorite Flavor")]
        public string SelectedFlavorId { get; set; }

        private readonly List<DropDown> Department;
        public IEnumerable<SelectListItem> FlavorItems
        {
            get { return new SelectList(Department, "Id", "Name"); }
        }

    }
}
