//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class document
    {
        public int docid { get; set; }
        public string doc_name { get; set; }
        public Nullable<int> empid { get; set; }
        public Nullable<System.DateTime> doc_expiry { get; set; }
        public Nullable<bool> alert { get; set; }
        public string filepath { get; set; }
    }
}
