//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_Personal
    {
        public int EMP_ID { get; set; }
        public string Emp_ID_ORG { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Department { get; set; }
        public string Location { get; set; }
        public string Designation { get; set; }
        public string ReportingTo { get; set; }
        public string Employee_type { get; set; }
        public string Religion { get; set; }
        public string Visa_status { get; set; }
        public string Emp_status { get; set; }
        public string Nationality { get; set; }
        public string DOB { get; set; }
        public string Gender { get; set; }
        public string Martial_status { get; set; }
        public string Accomodation { get; set; }
        public string Passport { get; set; }
        public string EmirateID { get; set; }
        public string BankName { get; set; }
        public string Bank_account { get; set; }
        public Nullable<int> camp { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public byte[] emp_image { get; set; }
        public Nullable<System.DateTime> joining { get; set; }
        public Nullable<bool> outsource { get; set; }
        public string remarks { get; set; }
    }
}
