//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.employee1 = new HashSet<employee>();
            this.employee11 = new HashSet<employee>();
            this.employee12 = new HashSet<employee>();
        }
    
        public int employeeId { get; set; }
        public Nullable<int> empi_ID_Org { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<int> department { get; set; }
        public Nullable<decimal> location { get; set; }
        public string Designation { get; set; }
        public Nullable<int> ReportingTo { get; set; }
        public Nullable<int> employeeType { get; set; }
        public string Religion { get; set; }
        public string visaStatus { get; set; }
        public string empStatus { get; set; }
        public Nullable<int> Nationality { get; set; }
        public string DOB { get; set; }
        public string gender { get; set; }
        public string martialStatus { get; set; }
        public string accomodation { get; set; }
        public Nullable<int> passport { get; set; }
        public Nullable<int> emirateID { get; set; }
        public Nullable<int> bankName { get; set; }
        public Nullable<int> bankAccount { get; set; }
        public Nullable<int> camp { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public string empImage { get; set; }
        public string joining { get; set; }
        public Nullable<int> outsource { get; set; }
        public string remarks { get; set; }
    
        public virtual bank bank { get; set; }
        public virtual camp camp1 { get; set; }
        public virtual department department1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee> employee1 { get; set; }
        public virtual employee employee2 { get; set; }
        public virtual employeeType employeeType1 { get; set; }
        public virtual status status { get; set; }
        public virtual location location1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee> employee11 { get; set; }
        public virtual employee employee3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee> employee12 { get; set; }
        public virtual employee employee4 { get; set; }
        public virtual Nationality Nationality1 { get; set; }
    }
}
