//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRMSEntities : DbContext
    {
        public HRMSEntities()
            : base("name=HRMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bank> banks { get; set; }
        public virtual DbSet<camp> camps { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<EMP_Personal> EMP_Personal { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<employeeType> employeeTypes { get; set; }
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Nationality> Nationalities { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<test> tests { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<visatype> visatypes { get; set; }
        public virtual DbSet<document> documents { get; set; }
    }
}
