//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Login()
        {
            this.Login1 = new HashSet<Login>();
            this.Login11 = new HashSet<Login>();
            this.Login12 = new HashSet<Login>();
        }
    
        public int UserCode { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
        public Nullable<int> MobileNumber { get; set; }
        public string Email { get; set; }
        public string EmpStatus { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> updateby { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
        public Nullable<int> PswdUpdatedBy { get; set; }
        public Nullable<System.DateTime> PswdUpdatedOn { get; set; }
        public string oldPswd { get; set; }
        public Nullable<int> NoOfAttempts { get; set; }
        public Nullable<int> NewCol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Login> Login1 { get; set; }
        public virtual Login Login2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Login> Login11 { get; set; }
        public virtual Login Login3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Login> Login12 { get; set; }
        public virtual Login Login4 { get; set; }
    }
}
